### PR TITLE
CRESP: Inverse Compton process

### PR DESCRIPTION
**Pull request by mogrodnik**
[WIP] Set of changes allowing to include IC losses in charged particle spectrum evolution. Current setup allows all processes to be selectively turned on/off, in which magnetic and CMB energy densities (umag, ucmb) are included in one cooling term 'ub'.
CMB energy density is based on redshift, currently set by one parameter "redshift" at namelist COSMIC_RAY_SPECTRUM.
IC process is by default switched on and may require new gold.

### CODE REVIEW

**Comment by gawrysz** [comment]
test this please

**Comment by mogrodnik** [comment]
Merged latest changes into cresp_ICprocess, fixed conflicts.
icomp_active switched off ATM - Let's check if the gold test is passed.
Run mcrwind with inverse Compton + synchrotron and without inverse Compton, everything seems to be in order.

test this please

**Comment by mogrodnik** [comment]
test this please

**Comment by gawrysz** [comment]
test this please

**Review by gawrysz — APPROVED** [review]

**Pull request merged**
