### PR TITLE
[WIP] Coriolis force in cylindrical coordinates

### PR DESCRIPTION
**Pull request by migueldvb**
Added Coriiolis force in the co-rotating frame for cylindrical coordinates.

### CODE REVIEW

**Comment by gawrysz** [comment]
I might be wrong but there should be also a radial term. The term in `cyl_geometry_source_terms` in src/base/gridgeometry.F90 provides only the part due to velocity relative to the grid but not due to `coriolis_omega`. Perhaps `advection_test` in cylindrical coords **with** non-zero rotation may be helpful in diagnosing the correctness of all terms. It would be good to leave a working `problem.par` that shows it and can be used for tests.

**Comment by Xarthisius** [comment]
Jenkins test this please.

**Comment by Piernik-Majster** [comment]
Can one of the admins verify this patch?

**Comment by Xarthisius** [comment]
add to whitelist

**Comment by Xarthisius** [comment]
retest this please

**Comment by migueldvb** [comment]
Thanks, I think it is true there is a radial term missing. I will try to setup a problem to test this in cylindrical coordinates.

**Comment by migueldvb** [comment]
I have added a radial term `-r*Omega**2` for coriolis_force in cylindrical coordinates.

**Pull request closed without merging**
