### PR TITLE
Add CR energy spectrum evolution algorithm

### PR DESCRIPTION
**Pull request by mogrodnik**
Cosmic ray energy spectrum algorithm (CRESP, read: "Cosmic Ray Energy SPectrum"), designed to model energy dependent CR transport, based on a Focker-Planck equation solver COSMOCR by F. Miniati (Computer Physics Communications 141, 2001, 17–38), enhanced with our own improvements and extensions. Currently suited to work with CR electrons.

### CODE REVIEW

**Comment by gawrysz** [comment]
Can one of the admins verify this patch?

**Comment by gawrysz** [comment]
Can one of the admins verify this patch?

**Comment by gawrysz** [comment]
Can one of the admins verify this patch?

**Comment by gawrysz** [comment]
Can one of the admins verify this patch?

**Comment by gawrysz** [comment]
Can one of the admins verify this patch?

**Comment by gawrysz** [comment]
Can one of the admins verify this patch?

**Comment by gawrysz** [comment]
Can one of the admins verify this patch?

**Comment by gawrysz** [comment]
Can one of the admins verify this patch?

**Comment by gawrysz** [comment]
Can one of the admins verify this patch?

**Comment by gawrysz** [comment]
Can one of the admins verify this patch?

**Comment by gawrysz** [comment]
Can one of the admins verify this patch?

**Comment by gawrysz** [comment]
Can one of the admins verify this patch?

**Comment by gawrysz** [comment]
Can one of the admins verify this patch?

**Comment by gawrysz** [comment]
Jenkins test this please

**Comment by gawrysz** [comment]
Jenkins test this please

**Comment by gawrysz** [comment]
Jenkins test this please

**Review by woolt — APPROVED** [review]

**Review by gawrysz — APPROVED** [review]
I suggest to update to the README file before merge (it is only cosmetics, but we should not refer to a "fork" after it is merged :) ).

**Comment by mogrodnik** [comment]
Allright, README has been restored, I expanded the PR comment instead.

**Pull request merged**
