### PR TITLE
An option for explicit diffusion restricted to act only below some level and interpolate to higher levels

### PR DESCRIPTION
**Pull request by gawrysz**
Since diffusion is limited by dx<sup>2</sup>, in AMR simulations it may severely slow down the computation even if the diffusion solver itself does not consume too much time. Assuming that we diffuse already smooth fields we may do the diffusion only up to certain level and keep the dt limited by other solvers. Finer levels may then be updated by high order interpolation (prolongation).

### CODE REVIEW

**Comment by gawrysz** [comment]
Difference between computed and analytic solution for CRtest with diffusion restricted to level 2. Note that most of the error is located on fine-coarse interface.
cr_tst_0001_Slice_z_err1

**Comment by gawrysz** [comment]
ToDo1: `diff_max_lev` may be changed from a stiff parameter to an automatically computed variable and be the highest level that does not limit the timestep more than other solvers do. Some sanity checks would be necessary as that limiting level may happen to be below base level :)

ToDo2: A check whether the diffused field is  smooth enough for particular restriction of the diffusion solver whould be nice. Unfortunately, without any prior assumptions,  the cost may be comparable to checking for Loechner refinement criterion. But a smooth field may only get smoother, so such a check should be integrated into routines that create the field to be diffused.

**Comment by gawrysz** [comment]
test this please

**Comment by gawrysz** [comment]
I'm not quite sure whether we really need this, unless there are productioin runs with really deep refinements that require explicit diffusiion and cannot work with implicit one. Even in such case I think that we need to merge #481 first and then resolve conflicts (these may be quite nontrivial as both PRs affect the came code).

**Comment by gawrysz** [comment]
Difference between computed and analytic solution for CRtest with diffusion restricted to level 2 after merging #481, resolving conflicts and other updates due to recent merges.

cr_tst_0001_Slice_z_err1

Small artifacts due to prolongation of a diagonal grandient are visible, but this is the most difficult case for any directional-split interpolation (such as bilinear or bi-cubic). 

The same quantity without restrictions for diffusion: 
cr_ts4_0001_Slice_z_err1

**Review by woolt — APPROVED** [review]

**Pull request merged**
