### PR TITLE
Misc

### PR DESCRIPTION
**Pull request by gawrysz**
Various small fixups and improvements.

### CODE REVIEW

**Comment by gawrysz** [comment]
Remaining suggestion of  `-frecursive` in multigrid.F90 will be fixed in #438 by 556641a.

**Comment by gawrysz** [comment]
test this please

**Comment by gawrysz** [comment]
test this please

**Comment by gawrysz** [comment]
test this please

**Comment by gawrysz** [comment]
test this please

**Comment by gawrysz** [comment]
test this please

**Review by woolt — APPROVED** [review]

**Pull request merged**
