### PR TITLE
Allow ionized fluid in the advection_test

### PR DESCRIPTION
**Pull request by gawrysz**

### CODE REVIEW

**Comment by Xarthisius** [comment]
jenkins test this please

**Comment by Xarthisius** [comment]
jenkins test this please

**Comment by Xarthisius** [comment]
jenkins test this please

**Comment by Xarthisius** [comment]
jenkins test this please

**Comment by Xarthisius** [comment]
jenkins test this please

**Comment by gawrysz** [comment]
jenkins test this please

**Pull request merged**
