### PR TITLE
[WPI] [base/non_inertial] Add support for polar coordinates

### PR DESCRIPTION
**Pull request by migueldvb**

### CODE REVIEW

**Comment by gawrysz** [comment]
Jenkins test this please

**Comment by gawrysz** [comment]
Miguel, it would be great to have a test problem for that non-inertial, coriolis stuff. I'd be more than happy to add it to the Jenkins tests.

**Comment by migueldvb** [comment]
I will add a test for polar coordinates.

**Comment by gawrysz** [comment]
Old, dead branch. Would require some attention before merge.

**Pull request closed without merging**
