### PR TITLE
Some small adjustments for Jenkins

### PR DESCRIPTION
**Pull request by gawrysz**

### CODE REVIEW

**Comment by gawrysz** [comment]
test this please

**Comment by gawrysz** [comment]
test this please

**Comment by gawrysz** [comment]
test this please

**Comment by gawrysz** [comment]
test this please

**Comment by gawrysz** [comment]
test this please

**Comment by gawrysz** [comment]
test this please

**Comment by Xarthisius** [comment]
test this please

**Comment by gawrysz** [comment]
test this please

**Comment by Xarthisius** [comment]
try again

**Comment by gawrysz** [comment]
test this please

**Comment by gawrysz** [comment]
test this please

**Comment by gawrysz** [comment]
test this please

**Comment by gawrysz** [comment]
test this please

**Comment by gawrysz** [comment]
test this please

**Comment by gawrysz** [comment]
test this please

**Comment by gawrysz** [comment]
test this please

**Comment by gawrysz** [comment]
test this please

**Comment by gawrysz** [comment]
test this please

**Comment by gawrysz** [comment]
test this please

**Comment by gawrysz** [comment]
test this please

**Pull request merged**
