### PR TITLE
particles in multicg

### PR DESCRIPTION
**Pull request by woolt**
multicg & parallel particles I/O & computation:

* parallel & serial mode for particles I/O
* particles migration across cg blocks in multicg and/or parallel mode
* fixes for tracing particles outside the domain
* fixes for timestep_nbody
* fixes, cleaning and cosmetics

### CODE REVIEW

**Comment by woolt** [comment]
jenkins test this please

**Comment by woolt** [comment]
jenkins test this please

**Comment by woolt** [comment]
jenkins test this please

**Comment by woolt** [comment]
jenkins test this please

**Comment by woolt** [comment]
jenkins test this please

**Review by gawrysz — APPROVED** [review]

**Pull request merged**
